"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTAppElementParams = void 0;
var BTAppElementParams = /** @class */ (function () {
    function BTAppElementParams() {
    }
    BTAppElementParams.getAttributeTypeMap = function () {
        return BTAppElementParams.attributeTypeMap;
    };
    BTAppElementParams.discriminator = undefined;
    BTAppElementParams.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "BTElementLocationParams"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "subelements",
            "baseName": "subelements",
            "type": "Array<BTAppElementChangeParams>"
        },
        {
            "name": "formatId",
            "baseName": "formatId",
            "type": "string"
        }
    ];
    return BTAppElementParams;
}());
exports.BTAppElementParams = BTAppElementParams;
