"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTAppElementContentEntryInfo = void 0;
var BTAppElementContentEntryInfo = /** @class */ (function () {
    function BTAppElementContentEntryInfo() {
    }
    BTAppElementContentEntryInfo.getAttributeTypeMap = function () {
        return BTAppElementContentEntryInfo.attributeTypeMap;
    };
    BTAppElementContentEntryInfo.discriminator = undefined;
    BTAppElementContentEntryInfo.attributeTypeMap = [
        {
            "name": "subelementId",
            "baseName": "subelementId",
            "type": "string"
        },
        {
            "name": "baseContent",
            "baseName": "baseContent",
            "type": "string"
        },
        {
            "name": "deltas",
            "baseName": "deltas",
            "type": "Array<BTAppElementContentDeltaInfo>"
        }
    ];
    return BTAppElementContentEntryInfo;
}());
exports.BTAppElementContentEntryInfo = BTAppElementContentEntryInfo;
