"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTAppElementReferenceParams = void 0;
var BTAppElementReferenceParams = /** @class */ (function () {
    function BTAppElementReferenceParams() {
    }
    BTAppElementReferenceParams.getAttributeTypeMap = function () {
        return BTAppElementReferenceParams.attributeTypeMap;
    };
    BTAppElementReferenceParams.discriminator = undefined;
    BTAppElementReferenceParams.attributeTypeMap = [
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string"
        },
        {
            "name": "targetDocumentId",
            "baseName": "targetDocumentId",
            "type": "string"
        },
        {
            "name": "targetElementId",
            "baseName": "targetElementId",
            "type": "string"
        },
        {
            "name": "targetConfiguration",
            "baseName": "targetConfiguration",
            "type": "string"
        },
        {
            "name": "isSketchOnly",
            "baseName": "isSketchOnly",
            "type": "boolean"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        },
        {
            "name": "parentChangeId",
            "baseName": "parentChangeId",
            "type": "string"
        },
        {
            "name": "sketchId",
            "baseName": "sketchId",
            "type": "string"
        },
        {
            "name": "sketchIds",
            "baseName": "sketchIds",
            "type": "Array<string>"
        },
        {
            "name": "idTag",
            "baseName": "idTag",
            "type": "string"
        },
        {
            "name": "targetVersionId",
            "baseName": "targetVersionId",
            "type": "string"
        },
        {
            "name": "pureSketch",
            "baseName": "pureSketch",
            "type": "boolean"
        },
        {
            "name": "targetMicroversionId",
            "baseName": "targetMicroversionId",
            "type": "string"
        },
        {
            "name": "idTagMicroversionId",
            "baseName": "idTagMicroversionId",
            "type": "string"
        },
        {
            "name": "hasDocumentMicroversions",
            "baseName": "hasDocumentMicroversions",
            "type": "boolean"
        },
        {
            "name": "partNumber",
            "baseName": "partNumber",
            "type": "string"
        },
        {
            "name": "returnError",
            "baseName": "returnError",
            "type": "boolean"
        },
        {
            "name": "trackNewVersions",
            "baseName": "trackNewVersions",
            "type": "boolean"
        },
        {
            "name": "updateSketchInfo",
            "baseName": "updateSketchInfo",
            "type": "boolean"
        }
    ];
    return BTAppElementReferenceParams;
}());
exports.BTAppElementReferenceParams = BTAppElementReferenceParams;
