"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTAppElementStartTransactionParams = void 0;
var BTAppElementStartTransactionParams = /** @class */ (function () {
    function BTAppElementStartTransactionParams() {
    }
    BTAppElementStartTransactionParams.getAttributeTypeMap = function () {
        return BTAppElementStartTransactionParams.attributeTypeMap;
    };
    BTAppElementStartTransactionParams.discriminator = undefined;
    BTAppElementStartTransactionParams.attributeTypeMap = [
        {
            "name": "parentChangeId",
            "baseName": "parentChangeId",
            "type": "string"
        },
        {
            "name": "returnError",
            "baseName": "returnError",
            "type": "boolean"
        }
    ];
    return BTAppElementStartTransactionParams;
}());
exports.BTAppElementStartTransactionParams = BTAppElementStartTransactionParams;
