"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTAppElementHistoryEntryInfo = void 0;
var BTAppElementHistoryEntryInfo = /** @class */ (function () {
    function BTAppElementHistoryEntryInfo() {
    }
    BTAppElementHistoryEntryInfo.getAttributeTypeMap = function () {
        return BTAppElementHistoryEntryInfo.attributeTypeMap;
    };
    BTAppElementHistoryEntryInfo.discriminator = undefined;
    BTAppElementHistoryEntryInfo.attributeTypeMap = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "changeId",
            "baseName": "changeId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }
    ];
    return BTAppElementHistoryEntryInfo;
}());
exports.BTAppElementHistoryEntryInfo = BTAppElementHistoryEntryInfo;
