"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTBetaCapabilityUserInfo = void 0;
var BTBetaCapabilityUserInfo = /** @class */ (function () {
    function BTBetaCapabilityUserInfo() {
    }
    BTBetaCapabilityUserInfo.getAttributeTypeMap = function () {
        return BTBetaCapabilityUserInfo.attributeTypeMap;
    };
    BTBetaCapabilityUserInfo.discriminator = undefined;
    BTBetaCapabilityUserInfo.attributeTypeMap = [
        {
            "name": "capabilityState",
            "baseName": "capabilityState",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "planId",
            "baseName": "planId",
            "type": "string"
        },
        {
            "name": "approvedAt",
            "baseName": "approvedAt",
            "type": "Date"
        },
        {
            "name": "removedAt",
            "baseName": "removedAt",
            "type": "Date"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "number"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "isGuest",
            "baseName": "isGuest",
            "type": "boolean"
        },
        {
            "name": "isLight",
            "baseName": "isLight",
            "type": "boolean"
        },
        {
            "name": "globalPermissions",
            "baseName": "globalPermissions",
            "type": "GlobalPermissionInfo"
        },
        {
            "name": "lastLoginTime",
            "baseName": "lastLoginTime",
            "type": "Date"
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "BTCompanySummaryInfo"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "number"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTBetaCapabilityUserInfo;
}());
exports.BTBetaCapabilityUserInfo = BTBetaCapabilityUserInfo;
