"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTBillingAccountParams = void 0;
var BTBillingAccountParams = /** @class */ (function () {
    function BTBillingAccountParams() {
    }
    BTBillingAccountParams.getAttributeTypeMap = function () {
        return BTBillingAccountParams.attributeTypeMap;
    };
    BTBillingAccountParams.discriminator = undefined;
    BTBillingAccountParams.attributeTypeMap = [
        {
            "name": "address",
            "baseName": "address",
            "type": "BTAddressInfo"
        },
        {
            "name": "forceCreate",
            "baseName": "forceCreate",
            "type": "boolean"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "companyPlan",
            "baseName": "companyPlan",
            "type": "boolean"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "companyId",
            "baseName": "companyId",
            "type": "string"
        },
        {
            "name": "planId",
            "baseName": "planId",
            "type": "string"
        },
        {
            "name": "seats",
            "baseName": "seats",
            "type": "number"
        },
        {
            "name": "domainPrefix",
            "baseName": "domainPrefix",
            "type": "string"
        },
        {
            "name": "paymentType",
            "baseName": "paymentType",
            "type": "number"
        },
        {
            "name": "trialPeriodDays",
            "baseName": "trialPeriodDays",
            "type": "number"
        },
        {
            "name": "promonthlyEnabled",
            "baseName": "promonthlyEnabled",
            "type": "boolean"
        },
        {
            "name": "resellerName",
            "baseName": "resellerName",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        }
    ];
    return BTBillingAccountParams;
}());
exports.BTBillingAccountParams = BTBillingAccountParams;
