"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTBillingAllowedPlansInfo = void 0;
var BTBillingAllowedPlansInfo = /** @class */ (function () {
    function BTBillingAllowedPlansInfo() {
    }
    BTBillingAllowedPlansInfo.getAttributeTypeMap = function () {
        return BTBillingAllowedPlansInfo.attributeTypeMap;
    };
    BTBillingAllowedPlansInfo.discriminator = undefined;
    BTBillingAllowedPlansInfo.attributeTypeMap = [
        {
            "name": "currentPlan",
            "baseName": "currentPlan",
            "type": "BTBillingPlanSummaryInfo"
        },
        {
            "name": "upgrades",
            "baseName": "upgrades",
            "type": "Array<BTBillingPlanSummaryInfo>"
        },
        {
            "name": "downgrades",
            "baseName": "downgrades",
            "type": "Array<BTBillingPlanSummaryInfo>"
        }
    ];
    return BTBillingAllowedPlansInfo;
}());
exports.BTBillingAllowedPlansInfo = BTBillingAllowedPlansInfo;
