"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTCloudStorageObjectListInfo = void 0;
var BTCloudStorageObjectListInfo = /** @class */ (function () {
    function BTCloudStorageObjectListInfo() {
    }
    BTCloudStorageObjectListInfo.getAttributeTypeMap = function () {
        return BTCloudStorageObjectListInfo.attributeTypeMap;
    };
    BTCloudStorageObjectListInfo.discriminator = undefined;
    BTCloudStorageObjectListInfo.attributeTypeMap = [
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BTCloudStorageObjectInfo>"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "pathToRoot",
            "baseName": "pathToRoot",
            "type": "Array<CloudObjectPathSegment>"
        }
    ];
    return BTCloudStorageObjectListInfo;
}());
exports.BTCloudStorageObjectListInfo = BTCloudStorageObjectListInfo;
