"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTCommentSubscriptionParams = void 0;
var BTCommentSubscriptionParams = /** @class */ (function () {
    function BTCommentSubscriptionParams() {
    }
    BTCommentSubscriptionParams.getAttributeTypeMap = function () {
        return BTCommentSubscriptionParams.attributeTypeMap;
    };
    BTCommentSubscriptionParams.discriminator = undefined;
    BTCommentSubscriptionParams.attributeTypeMap = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "subscribed",
            "baseName": "subscribed",
            "type": "boolean"
        }
    ];
    return BTCommentSubscriptionParams;
}());
exports.BTCommentSubscriptionParams = BTCommentSubscriptionParams;
