"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTComponentUsagesSummary = void 0;
var BTComponentUsagesSummary = /** @class */ (function () {
    function BTComponentUsagesSummary() {
    }
    BTComponentUsagesSummary.getAttributeTypeMap = function () {
        return BTComponentUsagesSummary.attributeTypeMap;
    };
    BTComponentUsagesSummary.discriminator = undefined;
    BTComponentUsagesSummary.attributeTypeMap = [
        {
            "name": "hierarchy",
            "baseName": "hierarchy_",
            "type": "BTStandardContentHierarchy"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "BTStandardContentHierarchy"
        }
    ];
    return BTComponentUsagesSummary;
}());
exports.BTComponentUsagesSummary = BTComponentUsagesSummary;
