"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTDocumentLabelParams = void 0;
var BTDocumentLabelParams = /** @class */ (function () {
    function BTDocumentLabelParams() {
    }
    BTDocumentLabelParams.getAttributeTypeMap = function () {
        return BTDocumentLabelParams.attributeTypeMap;
    };
    BTDocumentLabelParams.discriminator = undefined;
    BTDocumentLabelParams.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "documentIds",
            "baseName": "documentIds",
            "type": "Array<string>"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        },
        {
            "name": "parentLabelId",
            "baseName": "parentLabelId",
            "type": "string"
        }
    ];
    return BTDocumentLabelParams;
}());
exports.BTDocumentLabelParams = BTDocumentLabelParams;
