"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTDocumentMicroversionInfo = void 0;
var BTDocumentMicroversionInfo = /** @class */ (function () {
    function BTDocumentMicroversionInfo() {
    }
    BTDocumentMicroversionInfo.getAttributeTypeMap = function () {
        return BTDocumentMicroversionInfo.attributeTypeMap;
    };
    BTDocumentMicroversionInfo.discriminator = undefined;
    BTDocumentMicroversionInfo.attributeTypeMap = [
        {
            "name": "microversionId",
            "baseName": "microversionId",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "elementType",
            "baseName": "elementType",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "currentConfiguration",
            "baseName": "currentConfiguration",
            "type": "string"
        }
    ];
    return BTDocumentMicroversionInfo;
}());
exports.BTDocumentMicroversionInfo = BTDocumentMicroversionInfo;
