"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTDocumentScope = void 0;
var BTDocumentScope = /** @class */ (function () {
    function BTDocumentScope() {
    }
    BTDocumentScope.getAttributeTypeMap = function () {
        return BTDocumentScope.attributeTypeMap;
    };
    BTDocumentScope.discriminator = undefined;
    BTDocumentScope.attributeTypeMap = [
        {
            "name": "assertedElementType",
            "baseName": "assertedElementType",
            "type": "string"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "documentMicroversionId",
            "baseName": "documentMicroversionId",
            "type": "string"
        }
    ];
    return BTDocumentScope;
}());
exports.BTDocumentScope = BTDocumentScope;
