"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTElementLocationParams = void 0;
var BTElementLocationParams = /** @class */ (function () {
    function BTElementLocationParams() {
    }
    BTElementLocationParams.getAttributeTypeMap = function () {
        return BTElementLocationParams.attributeTypeMap;
    };
    BTElementLocationParams.discriminator = undefined;
    BTElementLocationParams.attributeTypeMap = [
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        }
    ];
    return BTElementLocationParams;
}());
exports.BTElementLocationParams = BTElementLocationParams;
