"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTElementRenameParams = void 0;
var BTElementRenameParams = /** @class */ (function () {
    function BTElementRenameParams() {
    }
    BTElementRenameParams.getAttributeTypeMap = function () {
        return BTElementRenameParams.attributeTypeMap;
    };
    BTElementRenameParams.discriminator = undefined;
    BTElementRenameParams.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "fromMetadataUpdate",
            "baseName": "fromMetadataUpdate",
            "type": "boolean"
        }
    ];
    return BTElementRenameParams;
}());
exports.BTElementRenameParams = BTElementRenameParams;
