"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTESDocumentHit = void 0;
var BTESDocumentHit = /** @class */ (function () {
    function BTESDocumentHit() {
    }
    BTESDocumentHit.getAttributeTypeMap = function () {
        return BTESDocumentHit.attributeTypeMap;
    };
    BTESDocumentHit.discriminator = undefined;
    BTESDocumentHit.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "sourceMap",
            "baseName": "sourceMap",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "highlightedFields",
            "baseName": "highlightedFields",
            "type": "{ [key: string]: Array<string>; }"
        }
    ];
    return BTESDocumentHit;
}());
exports.BTESDocumentHit = BTESDocumentHit;
