"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTExportModelEdge = void 0;
var BTExportModelEdge = /** @class */ (function () {
    function BTExportModelEdge() {
    }
    BTExportModelEdge.getAttributeTypeMap = function () {
        return BTExportModelEdge.attributeTypeMap;
    };
    BTExportModelEdge.discriminator = undefined;
    BTExportModelEdge.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "curve",
            "baseName": "curve",
            "type": "BTCurveDescription"
        },
        {
            "name": "vertices",
            "baseName": "vertices",
            "type": "Array<string>"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "BTExportModelEdgeGeometry"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTExportModelEdge;
}());
exports.BTExportModelEdge = BTExportModelEdge;
