"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTFeatureDefinitionResponse = void 0;
var BTFeatureDefinitionResponse = /** @class */ (function () {
    function BTFeatureDefinitionResponse() {
    }
    BTFeatureDefinitionResponse.getAttributeTypeMap = function () {
        return BTFeatureDefinitionResponse.attributeTypeMap;
    };
    BTFeatureDefinitionResponse.discriminator = undefined;
    BTFeatureDefinitionResponse.attributeTypeMap = [
        {
            "name": "feature",
            "baseName": "feature",
            "type": "BTMFeature"
        },
        {
            "name": "featureState",
            "baseName": "featureState",
            "type": "BTFeatureState"
        },
        {
            "name": "belScriptLibraryVersion",
            "baseName": "belScriptLibraryVersion",
            "type": "BTBelScriptLibraryVersion"
        },
        {
            "name": "sourceMicroversion",
            "baseName": "sourceMicroversion",
            "type": "string"
        },
        {
            "name": "rejectMicroversionSkew",
            "baseName": "rejectMicroversionSkew",
            "type": "boolean"
        },
        {
            "name": "libraryVersion",
            "baseName": "libraryVersion",
            "type": "number"
        },
        {
            "name": "serializationVersion",
            "baseName": "serializationVersion",
            "type": "string"
        },
        {
            "name": "microversionSkew",
            "baseName": "microversionSkew",
            "type": "boolean"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTFeatureDefinitionResponse;
}());
exports.BTFeatureDefinitionResponse = BTFeatureDefinitionResponse;
