"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTFSValue = void 0;
var BTFSValue = /** @class */ (function () {
    function BTFSValue() {
    }
    BTFSValue.getAttributeTypeMap = function () {
        return BTFSValue.attributeTypeMap;
    };
    BTFSValue.discriminator = undefined;
    BTFSValue.attributeTypeMap = [
        {
            "name": "valueObject",
            "baseName": "valueObject",
            "type": "any"
        },
        {
            "name": "configurationValueString",
            "baseName": "configurationValueString",
            "type": "string"
        },
        {
            "name": "typeTag",
            "baseName": "typeTag",
            "type": "string"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTFSValue;
}());
exports.BTFSValue = BTFSValue;
