"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTGlobalPermissionInfo = void 0;
var BTGlobalPermissionInfo = /** @class */ (function () {
    function BTGlobalPermissionInfo() {
    }
    BTGlobalPermissionInfo.getAttributeTypeMap = function () {
        return BTGlobalPermissionInfo.attributeTypeMap;
    };
    BTGlobalPermissionInfo.discriminator = undefined;
    BTGlobalPermissionInfo.attributeTypeMap = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>"
        }
    ];
    return BTGlobalPermissionInfo;
}());
exports.BTGlobalPermissionInfo = BTGlobalPermissionInfo;
