"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTGlobalTreeNodeInfo = void 0;
var BTGlobalTreeNodeInfo = /** @class */ (function () {
    function BTGlobalTreeNodeInfo() {
    }
    BTGlobalTreeNodeInfo.getAttributeTypeMap = function () {
        return BTGlobalTreeNodeInfo.attributeTypeMap;
    };
    BTGlobalTreeNodeInfo.discriminator = "jsonType";
    BTGlobalTreeNodeInfo.attributeTypeMap = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "BTOwnerInfo"
        },
        {
            "name": "treeHref",
            "baseName": "treeHref",
            "type": "string"
        },
        {
            "name": "resourceType",
            "baseName": "resourceType",
            "type": "string"
        },
        {
            "name": "isMutable",
            "baseName": "isMutable",
            "type": "boolean"
        },
        {
            "name": "isContainer",
            "baseName": "isContainer",
            "type": "boolean"
        },
        {
            "name": "canMove",
            "baseName": "canMove",
            "type": "boolean"
        },
        {
            "name": "hasPendingOwner",
            "baseName": "hasPendingOwner",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "isEnterpriseOwned",
            "baseName": "isEnterpriseOwned",
            "type": "boolean"
        },
        {
            "name": "modifiedAt",
            "baseName": "modifiedAt",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "BTUserBasicSummaryInfo"
        },
        {
            "name": "modifiedBy",
            "baseName": "modifiedBy",
            "type": "BTUserBasicSummaryInfo"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTGlobalTreeNodeInfo;
}());
exports.BTGlobalTreeNodeInfo = BTGlobalTreeNodeInfo;
