"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTIdentityInfo = void 0;
var BTIdentityInfo = /** @class */ (function () {
    function BTIdentityInfo() {
    }
    BTIdentityInfo.getAttributeTypeMap = function () {
        return BTIdentityInfo.attributeTypeMap;
    };
    BTIdentityInfo.discriminator = undefined;
    BTIdentityInfo.attributeTypeMap = [
        {
            "name": "team",
            "baseName": "team",
            "type": "BTTeamSummaryInfo"
        },
        {
            "name": "identityType",
            "baseName": "identityType",
            "type": "number"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "BTUserSummaryInfo"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTIdentityInfo;
}());
exports.BTIdentityInfo = BTIdentityInfo;
