"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTImportCloudObjectParams = void 0;
var BTImportCloudObjectParams = /** @class */ (function () {
    function BTImportCloudObjectParams() {
    }
    BTImportCloudObjectParams.getAttributeTypeMap = function () {
        return BTImportCloudObjectParams.attributeTypeMap;
    };
    BTImportCloudObjectParams.discriminator = undefined;
    BTImportCloudObjectParams.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean"
        },
        {
            "name": "mimeType",
            "baseName": "mimeType",
            "type": "string"
        },
        {
            "name": "notifyUser",
            "baseName": "notifyUser",
            "type": "boolean"
        },
        {
            "name": "ownerType",
            "baseName": "ownerType",
            "type": "BTImportCloudObjectParams.OwnerTypeEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "cloudStorageProvider",
            "baseName": "cloudStorageProvider",
            "type": "number"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        },
        {
            "name": "cloudStorageAccountId",
            "baseName": "cloudStorageAccountId",
            "type": "string"
        },
        {
            "name": "cloudObjectId",
            "baseName": "cloudObjectId",
            "type": "string"
        },
        {
            "name": "sizeBytes",
            "baseName": "sizeBytes",
            "type": "number"
        },
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "foreignId",
            "baseName": "foreignId",
            "type": "string"
        },
        {
            "name": "uploadId",
            "baseName": "uploadId",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "string"
        },
        {
            "name": "updateExistingImportFeatures",
            "baseName": "updateExistingImportFeatures",
            "type": "boolean"
        },
        {
            "name": "blobMicroversionId",
            "baseName": "blobMicroversionId",
            "type": "string"
        },
        {
            "name": "originalForeignId",
            "baseName": "originalForeignId",
            "type": "string"
        },
        {
            "name": "blobElementId",
            "baseName": "blobElementId",
            "type": "string"
        },
        {
            "name": "specifyUnits",
            "baseName": "specifyUnits",
            "type": "boolean"
        },
        {
            "name": "splitAssembliesIntoMultipleDocuments",
            "baseName": "splitAssembliesIntoMultipleDocuments",
            "type": "boolean"
        },
        {
            "name": "flattenAssemblies",
            "baseName": "flattenAssemblies",
            "type": "boolean"
        },
        {
            "name": "getyAxisIsUp",
            "baseName": "getyAxisIsUp",
            "type": "boolean"
        },
        {
            "name": "allowFaultyParts",
            "baseName": "allowFaultyParts",
            "type": "boolean"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }
    ];
    return BTImportCloudObjectParams;
}());
exports.BTImportCloudObjectParams = BTImportCloudObjectParams;
(function (BTImportCloudObjectParams) {
    var OwnerTypeEnum;
    (function (OwnerTypeEnum) {
        OwnerTypeEnum[OwnerTypeEnum["USER"] = 'USER'] = "USER";
        OwnerTypeEnum[OwnerTypeEnum["COMPANY"] = 'COMPANY'] = "COMPANY";
        OwnerTypeEnum[OwnerTypeEnum["ONSHAPE"] = 'ONSHAPE'] = "ONSHAPE";
    })(OwnerTypeEnum = BTImportCloudObjectParams.OwnerTypeEnum || (BTImportCloudObjectParams.OwnerTypeEnum = {}));
})(BTImportCloudObjectParams = exports.BTImportCloudObjectParams || (exports.BTImportCloudObjectParams = {}));
exports.BTImportCloudObjectParams = BTImportCloudObjectParams;
