"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTMaterialParams = void 0;
var BTMaterialParams = /** @class */ (function () {
    function BTMaterialParams() {
    }
    BTMaterialParams.getAttributeTypeMap = function () {
        return BTMaterialParams.attributeTypeMap;
    };
    BTMaterialParams.discriminator = undefined;
    BTMaterialParams.attributeTypeMap = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<BTMaterialPropertyParams>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "libraryName",
            "baseName": "libraryName",
            "type": "string"
        },
        {
            "name": "libraryReference",
            "baseName": "libraryReference",
            "type": "BTExternalElementReferenceInfo"
        }
    ];
    return BTMaterialParams;
}());
exports.BTMaterialParams = BTMaterialParams;
