"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTMetricsListParams = void 0;
var BTMetricsListParams = /** @class */ (function () {
    function BTMetricsListParams() {
    }
    BTMetricsListParams.getAttributeTypeMap = function () {
        return BTMetricsListParams.attributeTypeMap;
    };
    BTMetricsListParams.discriminator = undefined;
    BTMetricsListParams.attributeTypeMap = [
        {
            "name": "collectedMetrics",
            "baseName": "collectedMetrics",
            "type": "Array<BTMetricParams>"
        }
    ];
    return BTMetricsListParams;
}());
exports.BTMetricsListParams = BTMetricsListParams;
