"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTMetadataSchemaParams = void 0;
var BTMetadataSchemaParams = /** @class */ (function () {
    function BTMetadataSchemaParams() {
    }
    BTMetadataSchemaParams.getAttributeTypeMap = function () {
        return BTMetadataSchemaParams.attributeTypeMap;
    };
    BTMetadataSchemaParams.discriminator = undefined;
    BTMetadataSchemaParams.attributeTypeMap = [
        {
            "name": "objectType",
            "baseName": "objectType",
            "type": "number"
        },
        {
            "name": "ownerType",
            "baseName": "ownerType",
            "type": "number"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        }
    ];
    return BTMetadataSchemaParams;
}());
exports.BTMetadataSchemaParams = BTMetadataSchemaParams;
