"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTMetadataPropertyConfigParams = void 0;
var BTMetadataPropertyConfigParams = /** @class */ (function () {
    function BTMetadataPropertyConfigParams() {
    }
    BTMetadataPropertyConfigParams.getAttributeTypeMap = function () {
        return BTMetadataPropertyConfigParams.attributeTypeMap;
    };
    BTMetadataPropertyConfigParams.discriminator = undefined;
    BTMetadataPropertyConfigParams.attributeTypeMap = [
        {
            "name": "defaultValue",
            "baseName": "defaultValue",
            "type": "string"
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "publishState",
            "baseName": "publishState",
            "type": "number"
        },
        {
            "name": "schemaId",
            "baseName": "schemaId",
            "type": "string"
        },
        {
            "name": "propertyId",
            "baseName": "propertyId",
            "type": "string"
        },
        {
            "name": "minLength",
            "baseName": "minLength",
            "type": "number"
        },
        {
            "name": "maxLength",
            "baseName": "maxLength",
            "type": "number"
        },
        {
            "name": "minValue",
            "baseName": "minValue",
            "type": "number"
        },
        {
            "name": "maxValue",
            "baseName": "maxValue",
            "type": "number"
        },
        {
            "name": "minDate",
            "baseName": "minDate",
            "type": "Date"
        },
        {
            "name": "maxDate",
            "baseName": "maxDate",
            "type": "Date"
        },
        {
            "name": "minCount",
            "baseName": "minCount",
            "type": "number"
        },
        {
            "name": "maxCount",
            "baseName": "maxCount",
            "type": "number"
        },
        {
            "name": "multiline",
            "baseName": "multiline",
            "type": "boolean"
        },
        {
            "name": "enumValues",
            "baseName": "enumValues",
            "type": "Array<{ [key: string]: string; }>"
        }
    ];
    return BTMetadataPropertyConfigParams;
}());
exports.BTMetadataPropertyConfigParams = BTMetadataPropertyConfigParams;
