"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTMoveElementParams = void 0;
var BTMoveElementParams = /** @class */ (function () {
    function BTMoveElementParams() {
    }
    BTMoveElementParams.getAttributeTypeMap = function () {
        return BTMoveElementParams.attributeTypeMap;
    };
    BTMoveElementParams.discriminator = undefined;
    BTMoveElementParams.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "isCopy",
            "baseName": "isCopy",
            "type": "boolean"
        },
        {
            "name": "generateUnknownMessages",
            "baseName": "generateUnknownMessages",
            "type": "boolean"
        },
        {
            "name": "needNewVersion",
            "baseName": "needNewVersion",
            "type": "boolean"
        },
        {
            "name": "isDeepCopy",
            "baseName": "isDeepCopy",
            "type": "boolean"
        },
        {
            "name": "anchorElementId",
            "baseName": "anchorElementId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "targetDocumentId",
            "baseName": "targetDocumentId",
            "type": "string"
        },
        {
            "name": "sourceDocumentId",
            "baseName": "sourceDocumentId",
            "type": "string"
        },
        {
            "name": "sourceWorkspaceId",
            "baseName": "sourceWorkspaceId",
            "type": "string"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        },
        {
            "name": "ownerType",
            "baseName": "ownerType",
            "type": "number"
        },
        {
            "name": "isGroupAnchor",
            "baseName": "isGroupAnchor",
            "type": "boolean"
        },
        {
            "name": "targetWorkspaceId",
            "baseName": "targetWorkspaceId",
            "type": "string"
        },
        {
            "name": "elements",
            "baseName": "elements",
            "type": "Array<string>"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "string"
        },
        {
            "name": "isPublic",
            "baseName": "isPublic",
            "type": "boolean"
        },
        {
            "name": "versionName",
            "baseName": "versionName",
            "type": "string"
        },
        {
            "name": "importData",
            "baseName": "importData",
            "type": "Array<string>"
        },
        {
            "name": "elementOriginalToNewMap",
            "baseName": "elementOriginalToNewMap",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "isNewDocument",
            "baseName": "isNewDocument",
            "type": "boolean"
        },
        {
            "name": "ownerEmail",
            "baseName": "ownerEmail",
            "type": "string"
        }
    ];
    return BTMoveElementParams;
}());
exports.BTMoveElementParams = BTMoveElementParams;
