"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTNextPartNumbersParam = void 0;
var BTNextPartNumbersParam = /** @class */ (function () {
    function BTNextPartNumbersParam() {
    }
    BTNextPartNumbersParam.getAttributeTypeMap = function () {
        return BTNextPartNumbersParam.attributeTypeMap;
    };
    BTNextPartNumbersParam.discriminator = undefined;
    BTNextPartNumbersParam.attributeTypeMap = [
        {
            "name": "itemPartNumbers",
            "baseName": "itemPartNumbers",
            "type": "Array<BTNextPartNumberParam>"
        },
        {
            "name": "skipPartNumbers",
            "baseName": "skipPartNumbers",
            "type": "Array<string>"
        }
    ];
    return BTNextPartNumbersParam;
}());
exports.BTNextPartNumbersParam = BTNextPartNumbersParam;
