"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTObjectId = void 0;
var BTObjectId = /** @class */ (function () {
    function BTObjectId() {
    }
    BTObjectId.getAttributeTypeMap = function () {
        return BTObjectId.attributeTypeMap;
    };
    BTObjectId.discriminator = undefined;
    BTObjectId.attributeTypeMap = [
        {
            "name": "empty",
            "baseName": "empty",
            "type": "boolean"
        }
    ];
    return BTObjectId;
}());
exports.BTObjectId = BTObjectId;
