"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTPartQueryParams = void 0;
var BTPartQueryParams = /** @class */ (function () {
    function BTPartQueryParams() {
    }
    BTPartQueryParams.getAttributeTypeMap = function () {
        return BTPartQueryParams.attributeTypeMap;
    };
    BTPartQueryParams.discriminator = undefined;
    BTPartQueryParams.attributeTypeMap = [
        {
            "name": "linkDocumentId",
            "baseName": "linkDocumentId",
            "type": "string"
        },
        {
            "name": "queries",
            "baseName": "queries",
            "type": "Array<string>"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "string"
        }
    ];
    return BTPartQueryParams;
}());
exports.BTPartQueryParams = BTPartQueryParams;
