"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTPermissionSet = void 0;
var BTPermissionSet = /** @class */ (function () {
    function BTPermissionSet() {
    }
    BTPermissionSet.getAttributeTypeMap = function () {
        return BTPermissionSet.attributeTypeMap;
    };
    BTPermissionSet.discriminator = undefined;
    BTPermissionSet.attributeTypeMap = [];
    return BTPermissionSet;
}());
exports.BTPermissionSet = BTPermissionSet;
