"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTQueryRevisionParams = void 0;
var BTQueryRevisionParams = /** @class */ (function () {
    function BTQueryRevisionParams() {
    }
    BTQueryRevisionParams.getAttributeTypeMap = function () {
        return BTQueryRevisionParams.attributeTypeMap;
    };
    BTQueryRevisionParams.discriminator = undefined;
    BTQueryRevisionParams.attributeTypeMap = [
        {
            "name": "nodeIds",
            "baseName": "nodeIds",
            "type": "Array<string>"
        },
        {
            "name": "companyId",
            "baseName": "companyId",
            "type": "string"
        }
    ];
    return BTQueryRevisionParams;
}());
exports.BTQueryRevisionParams = BTQueryRevisionParams;
