"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTRbacRoleInfo = void 0;
var BTRbacRoleInfo = /** @class */ (function () {
    function BTRbacRoleInfo() {
    }
    BTRbacRoleInfo.getAttributeTypeMap = function () {
        return BTRbacRoleInfo.attributeTypeMap;
    };
    BTRbacRoleInfo.discriminator = undefined;
    BTRbacRoleInfo.attributeTypeMap = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "predefinedRole",
            "baseName": "predefinedRole",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTRbacRoleInfo;
}());
exports.BTRbacRoleInfo = BTRbacRoleInfo;
