"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTReleasePackageItem = void 0;
var BTReleasePackageItem = /** @class */ (function () {
    function BTReleasePackageItem() {
    }
    BTReleasePackageItem.getAttributeTypeMap = function () {
        return BTReleasePackageItem.attributeTypeMap;
    };
    BTReleasePackageItem.discriminator = undefined;
    BTReleasePackageItem.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "number"
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string"
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<BTReleasePackageItem>"
        },
        {
            "name": "mimeType",
            "baseName": "mimeType",
            "type": "string"
        },
        {
            "name": "microversionId",
            "baseName": "microversionId",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "partId",
            "baseName": "partId",
            "type": "string"
        },
        {
            "name": "elementType",
            "baseName": "elementType",
            "type": "number"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<BTReleasePackageItemError>"
        },
        {
            "name": "configurationKey",
            "baseName": "configurationKey",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "modifiedAt",
            "baseName": "modifiedAt",
            "type": "Date"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "companyId",
            "baseName": "companyId",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "modifiedBy",
            "baseName": "modifiedBy",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "diffThumbnailConfigurationKey",
            "baseName": "diffThumbnailConfigurationKey",
            "type": "string"
        },
        {
            "name": "initialRevision",
            "baseName": "initialRevision",
            "type": "string"
        },
        {
            "name": "revisionRuleId",
            "baseName": "revisionRuleId",
            "type": "string"
        },
        {
            "name": "isIncluded",
            "baseName": "isIncluded",
            "type": "boolean"
        },
        {
            "name": "remoteState",
            "baseName": "remoteState",
            "type": "number"
        },
        {
            "name": "smallThumbnailHref",
            "baseName": "smallThumbnailHref",
            "type": "string"
        },
        {
            "name": "isRevisionManaged",
            "baseName": "isRevisionManaged",
            "type": "boolean"
        },
        {
            "name": "partNumber",
            "baseName": "partNumber",
            "type": "string"
        },
        {
            "name": "rpid",
            "baseName": "rpid",
            "type": "string"
        },
        {
            "name": "obsoletionRevisionId",
            "baseName": "obsoletionRevisionId",
            "type": "string"
        }
    ];
    return BTReleasePackageItem;
}());
exports.BTReleasePackageItem = BTReleasePackageItem;
