"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTRevisionParams = void 0;
var BTRevisionParams = /** @class */ (function () {
    function BTRevisionParams() {
    }
    BTRevisionParams.getAttributeTypeMap = function () {
        return BTRevisionParams.attributeTypeMap;
    };
    BTRevisionParams.discriminator = undefined;
    BTRevisionParams.attributeTypeMap = [
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string"
        },
        {
            "name": "elementType",
            "baseName": "elementType",
            "type": "number"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "companyId",
            "baseName": "companyId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "partNumber",
            "type": "string"
        },
        {
            "name": "insertableId",
            "baseName": "insertableId",
            "type": "string"
        },
        {
            "name": "releaseId",
            "baseName": "releaseId",
            "type": "string"
        }
    ];
    return BTRevisionParams;
}());
exports.BTRevisionParams = BTRevisionParams;
