"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTReleasePackageItemParams = void 0;
var BTReleasePackageItemParams = /** @class */ (function () {
    function BTReleasePackageItemParams() {
    }
    BTReleasePackageItemParams.getAttributeTypeMap = function () {
        return BTReleasePackageItemParams.attributeTypeMap;
    };
    BTReleasePackageItemParams.discriminator = undefined;
    BTReleasePackageItemParams.attributeTypeMap = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<BTPropertyValueParam>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "partId",
            "baseName": "partId",
            "type": "string"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "isIncluded",
            "baseName": "isIncluded",
            "type": "boolean"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "partNumber",
            "type": "string"
        }
    ];
    return BTReleasePackageItemParams;
}());
exports.BTReleasePackageItemParams = BTReleasePackageItemParams;
