"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTSendGridDeliveryEventParams = void 0;
var BTSendGridDeliveryEventParams = /** @class */ (function () {
    function BTSendGridDeliveryEventParams() {
    }
    BTSendGridDeliveryEventParams.getAttributeTypeMap = function () {
        return BTSendGridDeliveryEventParams.attributeTypeMap;
    };
    BTSendGridDeliveryEventParams.discriminator = undefined;
    BTSendGridDeliveryEventParams.attributeTypeMap = [
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string"
        },
        {
            "name": "smtpid",
            "baseName": "smtpid",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        }
    ];
    return BTSendGridDeliveryEventParams;
}());
exports.BTSendGridDeliveryEventParams = BTSendGridDeliveryEventParams;
