"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTSimpleInfo = void 0;
var BTSimpleInfo = /** @class */ (function () {
    function BTSimpleInfo() {
    }
    BTSimpleInfo.getAttributeTypeMap = function () {
        return BTSimpleInfo.attributeTypeMap;
    };
    BTSimpleInfo.discriminator = undefined;
    BTSimpleInfo.attributeTypeMap = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return BTSimpleInfo;
}());
exports.BTSimpleInfo = BTSimpleInfo;
