"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTStandardContentCustomParameterParams = void 0;
var BTStandardContentCustomParameterParams = /** @class */ (function () {
    function BTStandardContentCustomParameterParams() {
    }
    BTStandardContentCustomParameterParams.getAttributeTypeMap = function () {
        return BTStandardContentCustomParameterParams.attributeTypeMap;
    };
    BTStandardContentCustomParameterParams.discriminator = undefined;
    BTStandardContentCustomParameterParams.attributeTypeMap = [
        {
            "name": "isDrivingConfiguration",
            "baseName": "isDrivingConfiguration",
            "type": "boolean"
        },
        {
            "name": "parameterValue",
            "baseName": "parameterValue",
            "type": "string"
        },
        {
            "name": "ownerType",
            "baseName": "ownerType",
            "type": "number"
        },
        {
            "name": "parameterType",
            "baseName": "parameterType",
            "type": "number"
        },
        {
            "name": "parameterName",
            "baseName": "parameterName",
            "type": "string"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        },
        {
            "name": "propertyId",
            "baseName": "propertyId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "standard",
            "baseName": "standard",
            "type": "string"
        },
        {
            "name": "types",
            "baseName": "types",
            "type": "string"
        },
        {
            "name": "componentDocumentId",
            "baseName": "componentDocumentId",
            "type": "string"
        },
        {
            "name": "disableProduction",
            "baseName": "disableProduction",
            "type": "boolean"
        },
        {
            "name": "productionVersionId",
            "baseName": "productionVersionId",
            "type": "string"
        },
        {
            "name": "testVersionId",
            "baseName": "testVersionId",
            "type": "string"
        }
    ];
    return BTStandardContentCustomParameterParams;
}());
exports.BTStandardContentCustomParameterParams = BTStandardContentCustomParameterParams;
