"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTStandardContentParameterDefinition = void 0;
var BTStandardContentParameterDefinition = /** @class */ (function () {
    function BTStandardContentParameterDefinition() {
    }
    BTStandardContentParameterDefinition.getAttributeTypeMap = function () {
        return BTStandardContentParameterDefinition.attributeTypeMap;
    };
    BTStandardContentParameterDefinition.discriminator = undefined;
    BTStandardContentParameterDefinition.attributeTypeMap = [
        {
            "name": "defaultValue",
            "baseName": "defaultValue",
            "type": "string"
        },
        {
            "name": "parameterId",
            "baseName": "parameterId",
            "type": "string"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "isCustomParameter",
            "baseName": "isCustomParameter",
            "type": "boolean"
        },
        {
            "name": "isDrivingConfiguration",
            "baseName": "isDrivingConfiguration",
            "type": "boolean"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        }
    ];
    return BTStandardContentParameterDefinition;
}());
exports.BTStandardContentParameterDefinition = BTStandardContentParameterDefinition;
