"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTTagParams = void 0;
var BTTagParams = /** @class */ (function () {
    function BTTagParams() {
    }
    BTTagParams.getAttributeTypeMap = function () {
        return BTTagParams.attributeTypeMap;
    };
    BTTagParams.discriminator = undefined;
    BTTagParams.attributeTypeMap = [
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        }
    ];
    return BTTagParams;
}());
exports.BTTagParams = BTTagParams;
