"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTTeamMemberParams = void 0;
var BTTeamMemberParams = /** @class */ (function () {
    function BTTeamMemberParams() {
    }
    BTTeamMemberParams.getAttributeTypeMap = function () {
        return BTTeamMemberParams.attributeTypeMap;
    };
    BTTeamMemberParams.discriminator = undefined;
    BTTeamMemberParams.attributeTypeMap = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "string"
        }
    ];
    return BTTeamMemberParams;
}());
exports.BTTeamMemberParams = BTTeamMemberParams;
