"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTUserEmailVerifyParams = void 0;
var BTUserEmailVerifyParams = /** @class */ (function () {
    function BTUserEmailVerifyParams() {
    }
    BTUserEmailVerifyParams.getAttributeTypeMap = function () {
        return BTUserEmailVerifyParams.attributeTypeMap;
    };
    BTUserEmailVerifyParams.discriminator = undefined;
    BTUserEmailVerifyParams.attributeTypeMap = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string"
        }
    ];
    return BTUserEmailVerifyParams;
}());
exports.BTUserEmailVerifyParams = BTUserEmailVerifyParams;
