"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTUserAgentVersion = void 0;
var BTUserAgentVersion = /** @class */ (function () {
    function BTUserAgentVersion() {
    }
    BTUserAgentVersion.getAttributeTypeMap = function () {
        return BTUserAgentVersion.attributeTypeMap;
    };
    BTUserAgentVersion.discriminator = undefined;
    BTUserAgentVersion.attributeTypeMap = [
        {
            "name": "patchVersion",
            "baseName": "patchVersion",
            "type": "number"
        },
        {
            "name": "majorVersion",
            "baseName": "majorVersion",
            "type": "number"
        },
        {
            "name": "minorVersion",
            "baseName": "minorVersion",
            "type": "number"
        }
    ];
    return BTUserAgentVersion;
}());
exports.BTUserAgentVersion = BTUserAgentVersion;
