"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BTWorkflowStateInfo = void 0;
var BTWorkflowStateInfo = /** @class */ (function () {
    function BTWorkflowStateInfo() {
    }
    BTWorkflowStateInfo.getAttributeTypeMap = function () {
        return BTWorkflowStateInfo.attributeTypeMap;
    };
    BTWorkflowStateInfo.discriminator = undefined;
    BTWorkflowStateInfo.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        }
    ];
    return BTWorkflowStateInfo;
}());
exports.BTWorkflowStateInfo = BTWorkflowStateInfo;
