"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigurationEntry = void 0;
var ConfigurationEntry = /** @class */ (function () {
    function ConfigurationEntry() {
    }
    ConfigurationEntry.getAttributeTypeMap = function () {
        return ConfigurationEntry.attributeTypeMap;
    };
    ConfigurationEntry.discriminator = undefined;
    ConfigurationEntry.attributeTypeMap = [
        {
            "name": "parameterId",
            "baseName": "parameterId",
            "type": "string"
        },
        {
            "name": "parameterValue",
            "baseName": "parameterValue",
            "type": "string"
        }
    ];
    return ConfigurationEntry;
}());
exports.ConfigurationEntry = ConfigurationEntry;
