"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestOptions = void 0;
var RequestOptions = /** @class */ (function () {
    function RequestOptions() {
    }
    RequestOptions.getAttributeTypeMap = function () {
        return RequestOptions.attributeTypeMap;
    };
    RequestOptions.discriminator = undefined;
    RequestOptions.attributeTypeMap = [
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string"
        },
        {
            "name": "stripeVersion",
            "baseName": "stripeVersion",
            "type": "string"
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotencyKey",
            "type": "string"
        },
        {
            "name": "stripeAccount",
            "baseName": "stripeAccount",
            "type": "string"
        },
        {
            "name": "connectTimeout",
            "baseName": "connectTimeout",
            "type": "number"
        },
        {
            "name": "readTimeout",
            "baseName": "readTimeout",
            "type": "number"
        }
    ];
    return RequestOptions;
}());
exports.RequestOptions = RequestOptions;
